maintenance:
  schedule:
    cleanup: "0 0 * * 0"  # 每週日執行
    optimize: "0 2 * * *"  # 每天凌晨2點執行
  paths:
    temp: "D:/temp"
    logs: "D:/logs"
  retention:
    log_days: 30
    temp_days: 7
  thresholds:
    disk_space: 85